"""test2

Revision ID: 61a883c92cfc
Revises: 9a0876f2ea38
Create Date: 2024-07-07 23:54:56.635958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a883c92cfc'
down_revision = '9a0876f2ea38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
