"""test

Revision ID: 9a0876f2ea38
Revises: a4be7939efa6
Create Date: 2024-07-07 23:51:01.504363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0876f2ea38'
down_revision = 'a4be7939efa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
