"""create table for users

Revision ID: bd519b482e6a
Revises: 8105e8321bda
Create Date: 2024-06-29 23:14:03.148903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd519b482e6a'
down_revision = '8105e8321bda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
